[build-system]
requires = [
  "poetry-core>=1.8.0",
  "poetry-dynamic-versioning>=1.9.1,<2.0",
  # list dependencies to work with PIP_NO_DEPS=1
  "MarkupSafe>=2.0",
  "dunamai>=1.25,<2.0",
  "jinja2>=3.0,<4.0",
  "packaging>=24.0",
  "tomlkit>=0.13",
]
build-backend = "poetry_dynamic_versioning.backend"

[project]
name = "geoh5-interop"
requires-python = ">=3.12,<3.15"

description = "A meta-package that groups together packages for interoperability between GEOH5 and other file formats."
license = "MIT"
license-files = [
    "LICENSE",
]
readme = "README.rst"
authors = [{ name = "Mira Geoscience", email = "support@mirageoscience.com" }]

dynamic = ["version", "classifiers"]
# version = "0.0.0.dev0"

dependencies = [
    "geoh5py >=0.13.0b1, ==0.13.*",
    "las-geoh5 >=0.3.3b1, ==0.3.*",
    "mira-omf >=3.4.0b1, ==3.4.*",
]

keywords = [
    "data format",
    "data",
    "earth science",
    "open science",
    "geoh5",
    "geology",
    "geophysics",
    "geoscience",
    "interoperability",
    "io",
    "lasio",
    "las-files",
    "log-ascii-standard",
    "mining",
    "well-logs",
    "wireline",
    "well-log",
]

[project.urls]
homepage = "https://www.mirageoscience.com/mining-industry-software/python-integration/"
repository = "https://github.com/MiraGeoscience/geoh5py-interop"

[tool.poetry]
requires-poetry = '>=2.0,<3.0'

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

include = [
    { path = "geoh5_interop/_version.py", format = ["sdist", "wheel"] },
]
version = "0.0.0.dev0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.9.1,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
bump = true
enable = true
fix-shallow-repository = true
strict = true
style = "pep440"
vcs = "git"

[tool.poetry-dynamic-versioning.substitution]
files = ["geoh5_interop/_version.py", "_version.json"]
patterns = [
    '''(^__version__\s*(?::.*?)?=\s*['"])[^'"]*(['"])''',
    '''(^{\s*"version"\s*:\s*")[^"]*("\s*})''',
]

[tool.poetry-dynamic-versioning.files."geoh5_interop/_version.py"]
persistent-substitution = true
initial-content = """
  __version__ = "0.0.0.dev0"
"""

[tool.poetry-dynamic-versioning.files."_version.json"]
persistent-substitution = true
initial-content = """
{ "version": "0.0.0.dev0" }
"""

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "B028",  # no-explicit-stacklevel for warnings.warn()
    "E501",  # line-too-long - code is reformatted (do not care about comments and docstring)
    "F401",  # unsused-import - covered by pycln
    "RUF005",  # collection-literal-concatenation - wrong suggestion with numpy arrays
]
select = [
    "A",  # flake8-builtins
    "B",  # flake8-bugbear
    "B006",  # Do not use mutable data structures for argument defaults
    "B9",  # flake8-bugbear opiniated warnings
    "BLE",  # flake8-blind-except
    "C4",  # flake8-comprehensions
    "C9",  # mccabe
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "RUF",  # ruff rules
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",  # pycodestyle warnings
]

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
# default formatting is just fine

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
scripts_are_modules = true
show_error_context = true
show_column_numbers = true
check_untyped_defs = true

[tool.pylint.main]
fail-on = ["F", "E", "W"]
fail-under = 10
jobs = 0

[tool.pylint.basic]
good-names = ["i", "j", "k", "x", "y", "z", "ex", "Run", "id", "_"]

[tool.pylint.design]
max-args = 9  # Maximum number of arguments for function / method.
              # (as long as not hitting too-many-positional-arguments)
max-attributes = 10  # Maximum number of attributes for a class (see R0902).
max-bool-expr = 6  # Maximum number of boolean expressions in an if statement (see R0916).
max-branches = 13  # Maximum number of branch for function / method body.
max-locals = 18  # Maximum number of locals for function / method body.
max-public-methods = 21  # Maximum number of public methods for a class (see R0904).
max-statements = 65  # Maximum number of statements in function / method body.
min-public-methods = 1  # Minimum number of public methods for a class (see R0903).

[tool.pylint."messages control"]
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "use-implicit-booleaness-not-comparison-to-string",
    "use-implicit-booleaness-not-comparison-to-zero",
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "fixme",
]
enable = ["c-extension-no-member"]

[tool.pylint.similarities]
min-similarity-lines = 7
