context:
  name: geoh5-interop
  version: 1.2.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - geoh5py >=0.11.0,<0.12.dev
    - las-geoh5 >=0.3.1,<0.4.dev
    - mira-omf >=3.3.1,<3.4.dev

tests:
  - python:
      imports:
      - geoh5_interop
      - geoh5py
      - las_geoh5
      - omf
      - properties
      pip_check: false  # something wrong with properties 0.6.1, but installation seems correct nonetheless
      python_version: ${{ python_min }}.*
  - script:
      - pip list
    requirements:
      run:
        - pip

about:
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration
  summary: 'A meta-package that groups together packages for interoperability between GEOH5 and other file formats.'

  description: |
    This meta-package collects the following packages:
    - [geoh5py](https://github.com/MiraGeoscience/geoh5py)
    - [mira-omf](https://github.com/MiraGeoscience/omf)
    - [las-geoh5](https://github.com/MiraGeoscience/las-geoh5)

    See the individual package documentation for more information.

  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
