name: Python analysis

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PIXI_VERSION: '0.70.2'

jobs:
  call-workflow-static-analysis:
    name: Static analysis
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-static_analysis.yml@v3.8.0-alpha.1
    permissions:
      contents: read
      pull-requests: read
    with:
      package-manager: 'pixi'
      virtual-repo-names: '["public-noremote-conda-dev"]'
      app-name: 'geoh5_interop'
      pixi-version: '${{ env.PIXI_VERSION }}'
      pixi-environment: 'py312'
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
  call-workflow-pytest-pypi:
    name: Pytest with Git repos
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest.yml@v3.8.0-alpha.1
    permissions:
      contents: read
      pull-requests: read
    with:
      package-manager: 'pixi'
      pixi-version: '${{ env.PIXI_VERSION }}'
      pixi-environments: '["py312", "py313", "py314"]'
      os: '["ubuntu-latest", "windows-latest"]'
      cache-number: 1
  call-workflow-pytest-conda:
    name: Pytest with Conda
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-pytest.yml@v3.8.0-alpha.1
    permissions:
      contents: read
      pull-requests: read
    with:
      package-manager: 'pixi'
      virtual-repo-names: '["public-noremote-conda-dev"]'
      pixi-version: '${{ env.PIXI_VERSION }}'
      pixi-environments: '["conda-py312", "conda-py313", "conda-py314"]'
      os: '["ubuntu-latest", "windows-latest"]'
      cache-number: 1
      codecov-reference-python-version: 'conda-py312'
      codecov-reference-os: '["windows-latest"]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
